### ISSUE TITLE
Feature Request: Option to exit process when time is finished

### ISSUE THREAD

**Issue by zach27** [jaden/SnapTimer#7]
Currently, the SnapTimer process continues running in the task bar after the "Time's up" dialog box is dismissed. I like to use a shortcut key (on Windows) to create a timer instance, but this only works if no other SnapTimer instances are running. This means I have to manually exit each instance after the time is up. It would be helpful if the process would exit upon dismissing the dialog box (either exit by default, or as an option in the settings). This would really simplify the housekeeping the user would have to do by hand.

**Comment by jaden** [comment]
Thanks for the comment. I can understand your use case, but I don't feel it would match the expected behavior for most users. With that said, it could always be a configuration option.

If you're able to submit a pull request that would be great. I have no idea when I'll have time to get back to SnapTimer.

**Comment by zach27** [comment]
I completely understand - that is reasonable. I haven't worked with Pascal before, but I may look into implementing this as an option eventually.

**Comment by jaden** [comment]
Cool. I would welcome a pull request if you get a chance to implement it.
